---
apiVersion: v2
type: application
appVersion: "2.4.2"
description: "wallabag is a self hostable application for saving web pages: Save and classify articles. Read them later. Freely. https://wallabag.org"
name: wallabag
version: 0.2.2
keywords:
  - wallabag
  - read-it-later
home: https://wallabag.org
icon: https://wallabag.org/user/themes/boxify/img/logo-wallabag-black.svg
sources:
  - https://github.com/wallabag/wallabag
engine: gotpl
maintainers:
  - name: Gavin Mogan
    email: helm@gavinmogan.com
annotations:
  artifacthub.io/changes: |
    - Actually working and tested 2.4.2 version
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: wallabag
      image: wallabag/wallabag:2.4.2
