apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wallabag.fullname" . }}
  labels:
{{ include "wallabag.labels" . | indent 4 }}
type: Opaque
data:
  postgres_host: "{{ .Values.wallabag.postgres.host | b64enc }}"
  postgres_port: "{{ .Values.wallabag.postgres.port | toString | b64enc }}"
  postgres_user: "{{ .Values.wallabag.postgres.user | b64enc }}"
  postgres_password: "{{ .Values.wallabag.postgres.password | b64enc }}"
  postgres_name: "{{ .Values.wallabag.postgres.name | b64enc }}"

  redis_host: "{{ .Values.wallabag.redis.host | b64enc }}"
  redis_password: "{{ .Values.wallabag.redis.password | b64enc }}"

{{- if .Values.wallabag.sentry }}
  sentry_dsn: "{{ .Values.wallabag.sentry | b64enc }}"
{{ end }}
