{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "wallabag.serviceAccountName" . }}
  labels:
{{ include "wallabag.labels" . | indent 4 }}
{{- end -}}
